version: "3.9"

services:
  api:
    build: .
    container_name: node-api-boilerplate
    command: yarn dev
    volumes:
      - .:/api
    ports:
      - 3000:3000
    environment:
      HOST: 0.0.0.0
      SWAGGER_HOST: localhost
      DB_HOST: mongodb://node-api-boilerplate-mongodb:27017

  mongodb:
    container_name: node-api-boilerplate-mongodb
    image: mongo:4.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: blog
      MONGO_INITDB_ROOT_PASSWORD: blog

  mongo-express:
    container_name: node-api-boilerplate-mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://blog:blog@node-api-boilerplate-mongodb:27017
